### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Igami** [cschuff/wattbewerb#1]
Es gibt keine LICENCE File in dem Repository. Ist das beabsichtigt? 
Falls nein füg doch bitte eine hinzu. Am besten eine freie wie Beispielsweise MIT.

https://choosealicense.com/licenses/mit/

**Comment by cschuff** [comment]
MIT steht in der package.json als license drin. Du kannst aber gerne noch zusätzlich ein LICENSE file hinzufügen. Rechte hast du doch, oder?

**Comment by Igami** [comment]
Schreiben kann ich nicht in wattbewerb/wattbewerb.

**Comment by cschuff** [comment]
Sollte jetzt gehen

**Comment by Igami** [comment]
Hat funktioniert.
